In [23]:
import pandas
df = pandas.read_csv("../data/City List.csv", index_col=0, encoding='utf-8')
#view our data. Note: 'NaN' indicates the value is missing
df

Empty DataFrame
Columns: []
Index: [Canggu, Ubud, Singapore, Bangkok, Kuala Lumpur, Chiang Mai, Jakarta, George Town, Sydney, Brighton, Gili Air, Kuta, Wellington, Saint Petersburg, Dubai, Melbourne, San Francisco, Kathmandu, Hong Kong, Moscow, Phuket, Osaka, Kota Kinabalu, Amsterdam, Las Palmas, Ghent, Bandung, Medan, London, Barcelona, Frankfurt, Siem Reap, Cape Town, Mumbai, Montreal, Seoul, Shanghai, Manila, Krabi, Yangon, Pai, Gainesville, Buenos Aires, Ho Chi Minh City, Washington, Tokyo, Utrecht, Cebu, Seminyak, Makassar, Yogyakarta, Stuttgart, Colombo, Ko Lanta, Prague, Perth, Istanbul, Hanoi, Paris, New York City, Edinburgh, Berlin, Lisbon, Nottingham, Dublin, Manchester, Cheltenham, Stockholm, Rome, Madrid, Bristol, Sliema, Los Angeles, Glasgow, Vienna, Tel Aviv, Reykjavik, Munich, Sofia, Budapest, Boston, Cardiff, Brussels, Marrakesh, Athens, Porto, Vancouver, Birmingham, Toulouse, Nice, Riyadh, Bucharest, Helsinki, Bordeaux, Sheffield, Riga, Leeds, Malaga, Copenhagen, Ljubljana, ...]

[745 rows x 0 columns]

In [11]:
data = open("../data/City List.csv", encoding='utf-8').read()
city = data.split()

In [12]:
def anydup(thelist):
  seen = set()
  for x in thelist:
    if x in seen: print(x, True)
    seen.add(x)
  return False

In [13]:
anydup(city)

Town True
City True
Las True
City True
City True
San True
City True
Ko True
Ko True
Ko True
Nang True
Ko True
Ko True
Phi True
Chiang True
Da True
San True
City True
City True
New True
del True
City True
San True
San True
City True
City True
San True
de True
York True
Lake True
San True
San True
City True
San True
Jose True
Louis True
La True
del True
Porto True
Salvador True
Bogota True
Santa True
Puerto True
Saint True
Louis True
Grande True
West True
Ko True
Reykjavik True
Port True
Sao True
Jose True
City True
Santa True
FL" True
City True
del True
Goiania True
Yaounde True
New True
Taipei True
City True
Los True
Palm True
Bay True
Miami True
Beach True
Beach True
Santa True
Port True
City True
Town True
Palm True
Springs True

False

In [17]:
count = 0
for x in city:
    if x == "Reykjavik": 
        count = count+1

In [18]:
print(count)

2

In [24]:
df.sort_values("City", ascending=True)

KeyError: 'City'